name: 'Nuwa Build Wheels'
description: 'Builds Python wheels for Nuwa/Nim projects using cibuildwheel'
author: 'Martin Eastwood'
inputs:
  nim-version:
    description: 'Nim version to use'
    required: false
    default: '2.0.0'
  cibw-version:
    description: 'Version of cibuildwheel to use'
    required: false
    default: '2.22.0'

runs:
  using: "composite"
  steps:
    # --- LINUX CONFIGURATION ---
    # Linux still needs CIBW_BEFORE_ALL because it builds inside a Docker container
    - name: Configure Linux Build
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "CIBW_BEFORE_ALL_LINUX<<EOF" >> $GITHUB_ENV
        echo "yum install -y xz curl gcc" >> $GITHUB_ENV
        echo "curl -L https://nim-lang.org/download/nim-${{ inputs.nim-version }}-linux_x64.tar.xz -o nim.tar.xz" >> $GITHUB_ENV
        echo "tar -xf nim.tar.xz" >> $GITHUB_ENV
        echo "mv nim-${{ inputs.nim-version }} /opt/nim" >> $GITHUB_ENV
        echo "ln -s /opt/nim/bin/nim /usr/bin/nim" >> $GITHUB_ENV
        echo "ln -s /opt/nim/bin/nimble /usr/bin/nimble" >> $GITHUB_ENV
        echo "rm nim.tar.xz" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    # --- WINDOWS CONFIGURATION ---
    # Install directly on Host (Runner), NOT inside cibuildwheel
    - name: Install Nim (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install nim --version ${{ inputs.nim-version }} -y
        # Add to GITHUB_PATH so it persists for the next step (cibuildwheel)
        echo "C:\tools\Nim\nim-${{ inputs.nim-version }}\bin" >> $GITHUB_PATH

    # --- MACOS CONFIGURATION ---
    # Install directly on Host (Runner), NOT inside cibuildwheel
    - name: Install Nim (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y
        # Add to GITHUB_PATH so it persists for the next step (cibuildwheel)
        echo "$HOME/.nimble/bin" >> $GITHUB_PATH

    # --- BUILD EXECUTION ---
    - name: Build Wheels
      shell: bash
      run: pipx run cibuildwheel==${{ inputs.cibw-version }}
